# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-05 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow', to='gram.Profile')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to='gram.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='poster',
        ),
        migrations.AddField(
            model_name='profile',
            name='relate',
            field=models.ManyToManyField(through='gram.Relationship', to='gram.Profile'),
        ),
    ]
