# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 10:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0002_profile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='relate',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.DeleteModel(
            name='Relationship',
        ),
    ]
