# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-06 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
