# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0008_auto_20181008_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imagecomments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gram.Comment'),
        ),
    ]
