# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0010_auto_20181008_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imagecomments',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='gram.Image'),
        ),
    ]
