# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-08 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gram', '0012_auto_20181008_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profilepic',
            field=models.ImageField(default=True, upload_to='picture/'),
        ),
    ]
